import { ProductCategory } from "@/types/product";

const demoProducts = [
  // 🍪 Cookies
  {
    name: "Brown Butter Chocolate Chip Cookies",
    category: ProductCategory.Cookies,
    price: "$4 each",
    description: "Crispy edges, gooey center. A fan favorite.",
    ingredients: [
      "brown butter",
      "chocolate chips",
      "vanilla",
      "eggs",
      "flour",
    ],
    imageUrl: "/IMG_0126.JPG",
  },
  {
    name: "Oatmeal Raisin Cookies",
    category: ProductCategory.Cookies,
    price: "$3.50 each",
    description: "Chewy and nostalgic with warm cinnamon spice.",
    ingredients: ["oats", "raisins", "cinnamon", "brown sugar", "butter"],
    imageUrl: "/IMG_0140.JPG",
  },
  {
    name: "Double Chocolate Crinkle Cookies",
    category: ProductCategory.Cookies,
    price: "$4 each",
    description: "Rich and fudgy with a powdered sugar crackle top.",
    ingredients: ["cocoa", "dark chocolate", "eggs", "flour", "powdered sugar"],
    imageUrl: "/IMG_0144.JPG",
  },
  {
    name: "Almond Shortbread Cookies",
    category: ProductCategory.Cookies,
    price: "$3 each",
    description: "Delicate, buttery, and topped with toasted almonds.",
    ingredients: ["butter", "almond flour", "sugar", "vanilla"],
    imageUrl: "/IMG_0159.JPG",
  },
  {
    name: "Iced Sugar Cookies",
    category: ProductCategory.Cookies,
    price: "$4 each",
    description: "Soft sugar cookies with hand-decorated icing.",
    ingredients: ["sugar", "butter", "vanilla", "eggs", "royal icing"],
    imageUrl: "/IMG_0160.JPG",
  },
  {
    name: "Snickerdoodle Cookies",
    category: ProductCategory.Cookies,
    price: "$3.50 each",
    description: "Classic cinnamon-sugar crackle with a soft center.",
    ingredients: ["butter", "sugar", "cinnamon", "cream of tartar", "flour"],
    imageUrl: "/IMG_0170.JPG",
  },

  // 🍫 Dessert Bars
  {
    name: "Salted Caramel Brownies",
    category: ProductCategory.DessertBars,
    price: "$4",
    description: "Rich dark chocolate brownie with gooey caramel swirl.",
    ingredients: [
      "dark chocolate",
      "caramel",
      "butter",
      "sugar",
      "eggs",
      "flour",
    ],
    imageUrl: "/IMG_0173.JPG",
  },
  {
    name: "Lemon Bars",
    category: ProductCategory.DessertBars,
    price: "$3.50",
    description: "Tangy lemon custard on a buttery shortbread crust.",
    ingredients: ["lemons", "eggs", "sugar", "butter", "flour"],
    imageUrl: "/IMG_0179.JPG",
  },
  {
    name: "Raspberry Crumble Bars",
    category: ProductCategory.DessertBars,
    price: "$4",
    description: "Tart raspberry jam layered with oat crumble.",
    ingredients: ["raspberries", "oats", "brown sugar", "flour", "butter"],
    imageUrl: "/IMG_0185.JPG",
  },
  {
    name: "S’mores Bars",
    category: ProductCategory.DessertBars,
    price: "$4",
    description: "Graham cracker base, fudge center, toasted marshmallow top.",
    ingredients: ["graham crackers", "chocolate", "marshmallows", "butter"],
    imageUrl: "/IMG_0210.JPG",
  },
  {
    name: "Peanut Butter Blondies",
    category: ProductCategory.DessertBars,
    price: "$3.75",
    description: "Chewy blondie with a peanut butter swirl.",
    ingredients: ["peanut butter", "brown sugar", "eggs", "vanilla", "flour"],
    imageUrl: "/IMG_0213.JPG",
  },
  {
    name: "Chocolate Mint Brownies",
    category: ProductCategory.DessertBars,
    price: "$4",
    description: "Fudgy brownies with a cool mint frosting layer.",
    ingredients: ["dark chocolate", "mint extract", "butter", "eggs", "sugar"],
    imageUrl: "/IMG_0231.JPG",
  },

  // 🧁 Muffins
  {
    name: "Blueberry Muffins",
    category: ProductCategory.Muffins,
    price: "$3.50",
    description: "Bursting with fresh blueberries and a sugar-crusted top.",
    ingredients: ["blueberries", "flour", "eggs", "sugar", "butter"],
    imageUrl: "/IMG_0242.JPG",
  },
  {
    name: "Banana Walnut Muffins",
    category: ProductCategory.Muffins,
    price: "$3.50",
    description: "Moist banana base with crunchy walnut topping.",
    ingredients: ["bananas", "walnuts", "sugar", "flour", "butter"],
    imageUrl: "/IMG_0258.JPG",
  },
  {
    name: "Chocolate Chip Muffins",
    category: ProductCategory.Muffins,
    price: "$3.75",
    description: "Light and fluffy with melty chocolate chips.",
    ingredients: ["chocolate chips", "eggs", "sugar", "flour", "butter"],
    imageUrl: "/IMG_3098.JPEG",
  },
  {
    name: "Zucchini Spice Muffins",
    category: ProductCategory.Muffins,
    price: "$3.25",
    description: "Cozy spices and a sneaky veggie boost.",
    ingredients: ["zucchini", "cinnamon", "nutmeg", "flour", "sugar"],
    imageUrl: "/IMG_3132.JPEG",
  },
  {
    name: "Lemon Poppy Muffins",
    category: ProductCategory.Muffins,
    price: "$3.50",
    description: "Bright lemon flavor with poppyseed crunch.",
    ingredients: ["lemons", "poppyseeds", "sugar", "eggs", "butter"],
    imageUrl: "/IMG_3275.JPEG",
  },
  {
    name: "Apple Cinnamon Muffins",
    category: ProductCategory.Muffins,
    price: "$3.50",
    description: "Diced apples and cinnamon swirl throughout.",
    ingredients: ["apples", "cinnamon", "eggs", "flour", "butter"],
    imageUrl: "/IMG_3312.JPEG",
  },

  // 🍰 Cakes
  {
    name: "Vanilla Maple Cake",
    category: ProductCategory.Cakes,
    price: "$28",
    description: "Soft vanilla cake sweetened with maple syrup.",
    ingredients: ["maple syrup", "vanilla", "flour", "butter", "eggs"],
    imageUrl: "/IMG_4102.JPEG",
  },
  {
    name: "Chocolate Layer Cake",
    category: ProductCategory.Cakes,
    price: "$30",
    description: "Rich cocoa sponge with creamy chocolate buttercream.",
    ingredients: ["cocoa", "flour", "eggs", "butter", "sugar"],
    imageUrl: "/IMG_4544.JPG",
  },
  {
    name: "Carrot Cake",
    category: ProductCategory.Cakes,
    price: "$28",
    description: "Moist spiced cake with cream cheese frosting.",
    ingredients: ["carrots", "cinnamon", "cream cheese", "sugar", "eggs"],
    imageUrl: "/IMG_4674.JPEG",
  },
  {
    name: "Lemon Raspberry Cake",
    category: ProductCategory.Cakes,
    price: "$30",
    description: "Zesty lemon layers with raspberry filling.",
    ingredients: ["lemons", "raspberries", "flour", "butter", "sugar"],
    imageUrl: "/icedcookie.jpg",
  },
  {
    name: "Coconut Cream Cake",
    category: ProductCategory.Cakes,
    price: "$32",
    description: "Fluffy coconut cake with whipped cream frosting.",
    ingredients: ["coconut milk", "flour", "whipped cream", "eggs", "sugar"],
    imageUrl: "/cake.jpg",
  },
  {
    name: "Almond Citrus Cake",
    category: ProductCategory.Cakes,
    price: "$30",
    description: "Bright orange and almond flour base, gluten free.",
    ingredients: ["almond flour", "oranges", "eggs", "honey", "baking soda"],
    imageUrl: "/brownies.jpg",
  },
];

export default demoProducts;
